### ISSUE TITLE
Ability to check that an original trial is properly enabled?

### ISSUE THREAD

**Issue by gi11es** [jpchase/ExperimentalFramework#52]
I'm experimenting with the Priority Hints origin trial. Unlike origin trials that add JS APIs, this one merely changes browser behaviour. As a result, I can't find a good way to verify that this origin trial is properly enabled. I.e. that my token is set up properly for my domain, the browser is seeing it and enabling the origin trial.

Is there an undocumented JS API, or Chrome feature that would let me verify that the origin trial is enabled for the current pageload? It can be something local only, I just need a way to check that it's working properly.

**Comment by jpchase** [comment]
Unfortunately, there isn't a way to directly check if an origin trial is enabled for a given page. We've relied on feature detection, which as you point out doesn't work for Priority Hints. 

We have a task on our backlog to add support for origin trials to DevTools (see crbug.com/607555). For your use case, would that be a good solution? That issue is not in our near-term plans, but it would help with prioritization to under if it would be helpful in your case.

**Comment by gi11es** [comment]
Yes, that would work. I’ve starred the bug. I ended up finding a way to verify that Priority Hints were working, but it would definitely save time not going on a goose chase if it stops working for whatever reason (which could be on our end) if this information was surfaced in devtools.
