### ISSUE TITLE
Document how to let a third-party script use an OT feature

### ISSUE THREAD

**Issue by jyasskin** [jpchase/ExperimentalFramework#8]
@beaufortfrancois asked that https://github.com/jpchase/OriginTrials/blob/gh-pages/developer-guide.md mention that when Origin 1 `<script src>`'s a script from Origin 2, Origin 1 needs to be opted into the Origin Trial for the Origin 2 script to be able to call functions from it.

**Comment by beaufortfrancois** [comment]
@beaufortfrancois would be so happy indeed ;)

**Comment by beaufortfrancois** [comment]
@jpchase @clelland WDYT?

**Comment by clelland** [comment]
SGTM -- if you want to write it up, we can get it merged. Otherwise, I'll see if I can find some way to word it.

**Comment by owencm** [comment]
I think it may be worth revisiting this. Since all OT features are security and privacy approved, it seems reasonable to me that anyone that can run script in the top level document can enable an OT.

I heard a use case from Nat and Ryan S about wanting to expose experimental perf metrics, but that they are only useful in this kind of 3rd party context.

Not sure how we'd make that work though as then I presume they'd need an OT key for every site they may be embedded in :/

**Comment by pyalot** [comment]
enabling OT programmatically would be useful.
